[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "napi-package-template"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {git = "https://github.com/napi-rs/napi-rs", branch = "rust-codegen-win32"}
napi-derive = {git = "https://github.com/napi-rs/napi-rs", branch = "rust-codegen-win32"}

[target.'cfg(all(unix, not(target_env = "musl")))'.dependencies]
jemallocator = {version = "0.3", features = ["disable_initial_exec_tls"]}

[target.'cfg(windows)'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = {git = "https://github.com/napi-rs/napi-rs", branch = "rust-codegen-win32"}

[profile.release]
opt-level = 's'
